// <auto-generated />
using Catalog.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.API.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "prod-001",
                            Description = "Laptop Gamer de alta eficiencia para desarrollo de software.",
                            Name = "Laptop Lenovo LOQ Gen 10",
                            Price = 1200.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = "prod-002",
                            Description = "Audífonos inalámbricos con cancelación de ruido premium.",
                            Name = "Audífonos Sony WH-1000XM4",
                            Price = 350.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = "prod-003",
                            Description = "Mouse gamer ergonómico con sensor de alta precisión.",
                            Name = "Mouse Logitech G502 Hero",
                            Price = 60.00m,
                            Stock = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
